# Generated by Django 4.1.6 on 2023-03-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_model", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_registration",
            name="email",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
