# Generated by Django 4.1.6 on 2023-03-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart_model", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart", name="amount_product", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cart", name="price_product", field=models.FloatField(),
        ),
    ]
